version: '3.4'

networks:
  todo_list: # Define the network at the top level
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: todo-db
    environment:
      POSTGRES_DB: todo-db
      POSTGRES_USER: todo-user
      POSTGRES_PASSWORD: password
    env_file:
      - app.env
    volumes:
      - todo_list:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - todo_list

  app:
    image: todo-list
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    environment:
      DB_SOURCE: postgres://todo-user:password@db:5432/todo-db?sslmode=disable
      PORT: 8080
    env_file:
      - app.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks: 
      - todo_list

volumes:
  todo_list:
