version: '3.4'

services:
  db:
    image: postgres:latest
    container_name: todo-db
    environment:
      POSTGRES_DB: todo-db
      POSTGRES_USER: todo-user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: todo-list
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    environment:
      DB_SOURCE: postgres://todo-user:password@db:5432/todo-db?sslmode=disable
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/tasks"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  db-data:
