version: '3.4'

networks:
  todo_list: # Define the network at the top level
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: todo-db
    environment:
      POSTGRES_DB: todo-db
      POSTGRES_USER: todo-user
      POSTGRES_PASSWORD: password
    volumes:
      - todo_list:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - todo_list

  migrate:
    image: migrate/migrate:v4.15.1
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations 
    entrypoint: [
      "sh", "-c",
      "migrate -path /migrations -database 'postgresql://todo_list_hl_user:XszUIRaM8P8BB5HvDMFa1CuRjFdZGpK8@dpg-cq7q9o6ehbks73943to0-a/todo_list_hl?sslmode=disable' up"
    ]
    restart: "on-failure"
    networks: 
      - todo_list

  app:
    image: todo-list
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    environment:
      DB_SOURCE: postgres://todo-user:password@db:5432/todo-db?sslmode=disable
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrate
    networks: 
      - todo_list

volumes:
  todo_list:
