name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-and-test:
    name: Build, Migrate, and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: todo-user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: todo-db
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate.linux-amd64 /usr/bin/migrate
        which migrate

    - name: Set up environment variables
      run: |
        cp app.env .env

    - name: Run Docker Compose
      run: make up

    - name: Run database migrations
      run: make migrateup

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test

    - name: Stop Docker Compose
      run: make down
